default:
  image: python:3.7-bullseye
  tags:
    - pangea-internal

stages:
  - lint
  - unit_tests
  - integration_tests
  - examples
  - publish

include:
  - /packages/pangea-sdk/.sdk-ci.yml
  - /packages/pangea-django/.django-ci.yml
  - /examples/.examples-ci.yml
