.pangea-sdk-base:
  before_script:
    - cd packages/pangea-sdk/
    - pip install poetry
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.pangea-sdk-test-base:
  variables:
  # Set each service test environment
    SERVICE_AUDIT_ENV: LVE
    SERVICE_AUTHN_ENV: LVE
    SERVICE_EMBARGO_ENV: LVE
    SERVICE_FILE_SCAN_ENV: LVE
    SERVICE_IP_INTEL_ENV: LVE
    SERVICE_DOMAIN_INTEL_ENV: LVE
    SERVICE_URL_INTEL_ENV: LVE
    SERVICE_FILE_INTEL_ENV: LVE
    SERVICE_USER_INTEL_ENV: LVE
    SERVICE_REDACT_ENV: LVE
    SERVICE_VAULT_ENV: LVE

  before_script:
    - echo $ENV
    - echo $CLOUD
  # Update environment variables
  # Domain
    - export PANGEA_INTEGRATION_DOMAIN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_DOMAIN_${ENV}_${CLOUD})"
  # Tokens
    - export PANGEA_INTEGRATION_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}_${CLOUD})"
  # Config IDs
    - export PANGEA_AUDIT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_2_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_2_${ENV}_${CLOUD})"

    - cd packages/pangea-sdk/
    - pip install poetry
    - poetry install

  parallel:
    matrix:
      - CLOUD: [AWS, GCP]

  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.pangea-sdk-publish-base:
  before_script:
    - cd packages/pangea-sdk/
    - pip install poetry
    - poetry install
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/pangea-sdk/**/*
      when: on_success

pangea-sdk-lint:
  extends: .pangea-sdk-base
  stage: lint
  script:
    - poetry run black .

pangea-sdk-generate-docs:
  extends: .pangea-sdk-base
  stage: lint
  allow_failure: true
  script:
    - poetry run python parse_module.py > python_sdk.json
  artifacts:
    expire_in: 1 month
    expose_as: python_sdk
    paths: ['packages/pangea-sdk/python_sdk.json']
    when: on_success

pangea-sdk-type-check:
  extends: .pangea-sdk-base
  stage: lint
  needs: []
  script:
    - poetry run mypy pangea tests

pangea-sdk-unit-testing:
  extends: .pangea-sdk-base
  stage: unit_tests
  script:
    - poetry run python -m unittest tests.unit

pangea-sdk-it-audit:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_AUDIT_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_audit

pangea-sdk-it-vault:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_VAULT_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_vault

pangea-sdk-it-authn:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_AUTHN_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_authn

pangea-sdk-it-embargo:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_EMBARGO_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_embargo

pangea-sdk-it-redact:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_REDACT_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_redact

pangea-sdk-it-file-scan:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_FILE_SCAN_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_file_scan
  rules:
    - if: '$CLOUD == "GCP"'
      allow_failure: true
    - if: '$CLOUD != "GCP"'
      allow_failure: false

pangea-sdk-it-ip-intel:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_IP_INTEL_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_intel.TestIPIntel

pangea-sdk-it-domain-intel:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_DOMAIN_INTEL_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_intel.TestDomainIntel

pangea-sdk-it-url-intel:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_URL_INTEL_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_intel.TestURLIntel

pangea-sdk-it-user-intel:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_USER_INTEL_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_intel.TestUserIntel

pangea-sdk-it-file-intel:
  extends: .pangea-sdk-test-base
  stage: integration_tests
  variables:
    ENV: ${SERVICE_FILE_INTEL_ENV}
  script:
    - poetry run python -m unittest tests.integration.test_intel.TestFileIntel

.pangea-sdk-staging-tests:
  extends: .pangea-sdk-test-base
  variables:
    ENV: STG
  # Set each service test environment
    SERVICE_AUDIT_ENV: STG
    SERVICE_AUTHN_ENV: STG
    SERVICE_EMBARGO_ENV: STG
    SERVICE_FILE_SCAN_ENV: STG
    SERVICE_IP_INTEL_ENV: STG
    SERVICE_DOMAIN_INTEL_ENV: STG
    SERVICE_URL_INTEL_ENV: STG
    SERVICE_FILE_INTEL_ENV: STG
    SERVICE_USER_INTEL_ENV: STG
    SERVICE_REDACT_ENV: STG
    SERVICE_VAULT_ENV: STG

  script:
    - poetry run python -m unittest tests.integration

# TODO: Add asyncio tests when upgrade python 3.8

pangea-sdk-publish:
  extends: .pangea-sdk-publish-base
  stage: publish
  script:
    - poetry build
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
